services:
  server:
    image: "itzg/minecraft-server:2024.2.2-java21-alpine"
    stdin_open: true
    tty: true
    environment:
      EULA: true
      INIT_MEMORY: "512M"
      MAX_MEMORY: "4G"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE: "42.2.17"
      MOTD: "§6§lserveur goatesque"
      SNOOPER_ENABLED: false
      RCON_PASSWORD: "!rY#B!g5^nLteMJ4c2*JXkAb#KT4MJJ%E!sCLDSS"
      ICON: 'https://cdn.discordapp.com/icons/769696736158548060/bcc69d997347ead8115f5a5036ec8809.png?size=2048&format=webp&quality=lossless&width=0&height=256'
      #
      # MODRINTH_MODPACK: "/smp asile 1.1.0.mrpack"
      # MODRINTH_LOADER: "forge"
      # MOD_PLATFORM: "modrinth"
    ports:
      - "0.0.0.0:25565:25565"
      - "0.0.0.0:24454:24454/udp"
    restart: "unless-stopped"
    volumes:
      - "./data:/data:rw"
        # - "./smp asile 1.1.0.mrpack:/smp asile 1.1.0.mrpack:ro"
